/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125TermsRouteImport } from './routes/{-$locale}/terms'
import { Route as Char123LocaleChar125PrivacyRouteImport } from './routes/{-$locale}/privacy'
import { Route as Char123LocaleChar125DashboardRouteImport } from './routes/{-$locale}/dashboard'
import { Route as Char123LocaleChar125AuthAuthViewRouteImport } from './routes/{-$locale}/auth/$authView'

const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/{-$locale}/',
    path: '/{-$locale}/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125TermsRoute =
  Char123LocaleChar125TermsRouteImport.update({
    id: '/{-$locale}/terms',
    path: '/{-$locale}/terms',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125PrivacyRoute =
  Char123LocaleChar125PrivacyRouteImport.update({
    id: '/{-$locale}/privacy',
    path: '/{-$locale}/privacy',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125DashboardRoute =
  Char123LocaleChar125DashboardRouteImport.update({
    id: '/{-$locale}/dashboard',
    path: '/{-$locale}/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125AuthAuthViewRoute =
  Char123LocaleChar125AuthAuthViewRouteImport.update({
    id: '/{-$locale}/auth/$authView',
    path: '/{-$locale}/auth/$authView',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}/dashboard': typeof Char123LocaleChar125DashboardRoute
  '/{-$locale}/privacy': typeof Char123LocaleChar125PrivacyRoute
  '/{-$locale}/terms': typeof Char123LocaleChar125TermsRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/auth/$authView': typeof Char123LocaleChar125AuthAuthViewRoute
}
export interface FileRoutesByTo {
  '/{-$locale}/dashboard': typeof Char123LocaleChar125DashboardRoute
  '/{-$locale}/privacy': typeof Char123LocaleChar125PrivacyRoute
  '/{-$locale}/terms': typeof Char123LocaleChar125TermsRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/auth/$authView': typeof Char123LocaleChar125AuthAuthViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}/dashboard': typeof Char123LocaleChar125DashboardRoute
  '/{-$locale}/privacy': typeof Char123LocaleChar125PrivacyRoute
  '/{-$locale}/terms': typeof Char123LocaleChar125TermsRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/auth/$authView': typeof Char123LocaleChar125AuthAuthViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}/dashboard'
    | '/{-$locale}/privacy'
    | '/{-$locale}/terms'
    | '/{-$locale}'
    | '/{-$locale}/auth/$authView'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}/dashboard'
    | '/{-$locale}/privacy'
    | '/{-$locale}/terms'
    | '/{-$locale}'
    | '/{-$locale}/auth/$authView'
  id:
    | '__root__'
    | '/{-$locale}/dashboard'
    | '/{-$locale}/privacy'
    | '/{-$locale}/terms'
    | '/{-$locale}/'
    | '/{-$locale}/auth/$authView'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125DashboardRoute: typeof Char123LocaleChar125DashboardRoute
  Char123LocaleChar125PrivacyRoute: typeof Char123LocaleChar125PrivacyRoute
  Char123LocaleChar125TermsRoute: typeof Char123LocaleChar125TermsRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  Char123LocaleChar125AuthAuthViewRoute: typeof Char123LocaleChar125AuthAuthViewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/terms': {
      id: '/{-$locale}/terms'
      path: '/{-$locale}/terms'
      fullPath: '/{-$locale}/terms'
      preLoaderRoute: typeof Char123LocaleChar125TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/privacy': {
      id: '/{-$locale}/privacy'
      path: '/{-$locale}/privacy'
      fullPath: '/{-$locale}/privacy'
      preLoaderRoute: typeof Char123LocaleChar125PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/dashboard': {
      id: '/{-$locale}/dashboard'
      path: '/{-$locale}/dashboard'
      fullPath: '/{-$locale}/dashboard'
      preLoaderRoute: typeof Char123LocaleChar125DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/auth/$authView': {
      id: '/{-$locale}/auth/$authView'
      path: '/{-$locale}/auth/$authView'
      fullPath: '/{-$locale}/auth/$authView'
      preLoaderRoute: typeof Char123LocaleChar125AuthAuthViewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125DashboardRoute: Char123LocaleChar125DashboardRoute,
  Char123LocaleChar125PrivacyRoute: Char123LocaleChar125PrivacyRoute,
  Char123LocaleChar125TermsRoute: Char123LocaleChar125TermsRoute,
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  Char123LocaleChar125AuthAuthViewRoute: Char123LocaleChar125AuthAuthViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
