name: Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  NODE_VERSION: "20"
  PNPM_VERSION: "10"

jobs:
  # 检测变更
  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      web: ${{ steps.filter.outputs.web }}
      server: ${{ steps.filter.outputs.server }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect file changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            web:
              - 'apps/web/**'
              - 'package.json'
              - 'pnpm-lock.yaml'
            server:
              - 'apps/server/**'
              - 'package.json'
              - 'pnpm-lock.yaml'

  # 构建和测试
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.web == 'true' || needs.detect-changes.outputs.server == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm run check-types
        continue-on-error: true

      - name: Lint & Format check
        run: pnpm run check
        continue-on-error: true

      - name: Build web (if changed)
        if: needs.detect-changes.outputs.web == 'true'
        run: pnpm run build
        working-directory: ./apps/web

      - name: Build server (if changed)
        if: needs.detect-changes.outputs.server == 'true'
        run: pnpm run build
        working-directory: ./apps/server

      - name: Summary
        if: success()
        run: |
          echo "### ✅ Build Successful" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "All checks passed! Ready for review." >> $GITHUB_STEP_SUMMARY
